return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "basedpyright",
        "pylint",
        "black",
        "debugpy",
        "lua-language-server",
        "stylua",
        "typescript-language-server",
        "eslint-lsp",
        "prettier",
        "html-lsp",
        "css-lsp",
        "json-lsp",
        "yaml-language-server",
        "marksman",
        "tailwindcss-language-server",
        "clangd",
        "bash-language-server",
        "shfmt",
        "shellcheck",
        "bicep-lsp",
        "azure-pipelines-language-server",
      },
    },
  },
}
